import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("production readiness documentation", () => {
  it("keeps the core-only production readiness gate linked from the goal", () => {
    const goal = readFileSync("docs/goal.md", "utf8");
    const readiness = readFileSync("docs/production-readiness.md", "utf8");
    const runbook = readFileSync("docs/production-runbook.md", "utf8");

    expect(goal).toContain("[Production Readiness Gate](./production-readiness.md)");
    expect(readiness).toContain("# Production Readiness Gate");
    expect(readiness).toContain("[Production Runbook](./production-runbook.md)");
    expect(readiness).toContain("Out of Scope for Core Production Readiness");
    expect(readiness).toContain("Gameplay logic");
    expect(readiness).toContain("npm run verify:production-readiness");
    expect(readiness).toContain("npm run smoke:fxserver-core");
    expect(readiness).toContain("SDB_FIVEM_LICENSE_KEY");
    expect(readiness).toContain("sv_licenseKey");
    expect(readiness).toContain('status: "official"');
    expect(readiness).toContain("real FXServer smoke transcript");
    expect(readiness).toContain("Smoke run id:");
    expect(readiness).toContain("FXServer transcript and all supplied disposable-runner evidence artifacts");
    expect(readiness).toContain("UUID-shaped");
    expect(readiness).toContain("complete disposable-runner evidence bundle");
    expect(readiness).toContain("non-empty bind address");
    expect(readiness).toContain("Recorded timing fields must be numeric");
    expect(readiness).toContain("all recorded primary and alternate connect ports must be integers between `1` and `65535`");
    expect(readiness).toContain("maximum observed count must match those samples");
    expect(readiness).toContain("alternate probe targets when present");
    expect(readiness).toContain("alternate `/players.json` targets when present");
    expect(readiness).toContain("server/client verifier commands with all evidence flags");
    expect(readiness).toContain("recorded alternate FiveM connect URIs must be well-formed");
    expect(readiness).toContain("the advertised connect host must not be the unresolved `<server-ip>` placeholder");
    expect(readiness).toContain("include any recorded alternate FiveM connect URIs");
    expect(readiness).toContain("connect target must match the advertised network/player probe targets and socket port");
    expect(readiness).toContain("the launcher file must belong to the same smoke run");
    expect(readiness).toContain("point at the same connect target");
    expect(readiness).toContain("include client launcher evidence");
    expect(readiness).toContain("complete client-required verifier section");
    expect(readiness).toContain("section being treated as passing evidence");
    expect(runbook).toContain("# Production Runbook");
    expect(runbook).toContain("SDB_SPACETIME_URI");
    expect(runbook).toContain("SDB_FIVEM_COMMAND_ENDPOINT");
    expect(runbook).toContain("ensure sdb_runtime");
    expect(runbook).toContain("npm run start:admin");
    expect(runbook).toContain("npm run verify:production-readiness");
    expect(runbook).toContain("Smoke run id:");
    expect(runbook).toContain("stamps `fxserver-smoke.log`");
    expect(runbook).toContain("reject malformed");
    expect(runbook).toContain("complete runner evidence bundle");
    expect(runbook).toContain("must show `Client checks required: yes` and a `Client launcher path:`");
    expect(runbook).toContain("maximum observed count matches those samples");
    expect(runbook).toContain("alternate probe targets report HTTP 200 when present");
    expect(runbook).toContain("must be non-empty");
    expect(runbook).toContain("must also match the advertised `/info.json` and `/players.json` probe targets plus the socket-probe port");
    expect(runbook).toContain("The `Bind address:` recorded in `connect-info.txt` must be non-empty");
    expect(runbook).toContain("smoke timing fields recorded in `connect-info.txt` must be numeric");
    expect(runbook).toContain("All primary and alternate connect ports recorded in `connect-info.txt` must be integers between `1` and `65535`");
    expect(runbook).toContain("recorded alternate FiveM connect URIs must be well-formed");
    expect(runbook).toContain("the advertised connect host must not be the unresolved `<server-ip>` placeholder");
    expect(runbook).toContain("any recorded alternate FiveM connect URIs");
    expect(runbook).toContain("production readiness verifies that launcher file has the same smoke run id");
    expect(runbook).toContain("alternate detected IPv4 launch links");
    expect(runbook).toContain("alternate FiveM connect URIs for operator-facing interfaces");
    expect(runbook).toContain("browser-side `/info.json` and `/players.json` checks for each listed connect target");
    expect(runbook).toContain("Use the reachability table");
    expect(runbook).toContain("terminal output and reminders print those alternate FiveM URIs");
    expect(runbook).toContain("fail preflight before staging FXServer");
    expect(runbook).toContain("when `SDB_FIVEM_LICENSE_KEY` is missing");
    expect(runbook).toContain("not an integer between `1` and `65535`");
    expect(runbook).toContain("not a positive finite number");
    expect(runbook).toContain("not a non-negative finite number");
    expect(runbook).toContain("`--prepare-only` still validates generated-evidence inputs");
    expect(runbook).toContain("client-required connect host before staging files");
    expect(runbook).toContain("`SDB_FXSERVER_BIND_ADDRESS` or `--bind-address` is blank or whitespace-only");
    expect(runbook).toContain("`SDB_FXSERVER_CONNECT_HOST` or `--connect-host` is blank or whitespace-only");
    expect(runbook).toContain("`SDB_FXSERVER_ARTIFACT_URL` or `--artifact-url` is blank or whitespace-only");
    expect(runbook).toContain("complete client-required section");
    expect(runbook).toContain("section being treated as passing evidence");
  });
});
