import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

function read(path: string): string {
  return readFileSync(path, "utf8");
}

describe("QBCore compatibility resource facade", () => {
  it("declares a qb-core-compatible FiveM resource facade over sdb_runtime", () => {
    expect(existsSync("resources/[compat]/qb-core/fxmanifest.lua")).toBe(true);

    const manifest = read("resources/[compat]/qb-core/fxmanifest.lua");
    expect(manifest).toContain("fx_version 'cerulean'");
    expect(manifest).toContain("game 'gta5'");
    expect(manifest).toContain("provide 'qb-core'");
    expect(manifest).toContain("dependency 'sdb_runtime'");
    expect(manifest).toContain("client_script 'client/main.lua'");
    expect(manifest).toContain("server_script 'server/main.lua'");
  });

  it("exports the server QBCore object and direct player getter through sdb_runtime", () => {
    const server = read("resources/[compat]/qb-core/server/main.lua");

    expect(server).toContain("local QBCore = {");
    expect(server).toContain("Functions = {}");
    expect(server).toContain("Shared = exports.sdb_runtime:GetQbShared()");
    expect(server).toContain("Config = {");
    expect(server).toContain("Commands = {");
    expect(server).toContain("List = {}");
    expect(server).toContain("IgnoreList = {");
    expect(server).toContain("ServerCallbacks = {}");
    expect(server).toContain("ClientCallbacks = {}");
    expect(server).toContain("function QBCore.Functions.GetPlayer(source)");
    expect(server).toContain("return exports.sdb_runtime:GetQbPlayer(source)");
    expect(server).toContain("function QBCore.Functions.GetQBPlayers()");
    expect(server).toContain("QBCore.Players = exports.sdb_runtime:GetQbPlayers()");
    expect(server).toContain("return QBCore.Players");
    expect(server).toContain("function QBCore.Functions.GetPlayers()");
    expect(server).toContain("return exports.sdb_runtime:GetQbPlayerSources()");
    expect(server).toContain("function QBCore.Functions.GetIdentifier(source, idType)");
    expect(server).toContain("return exports.sdb_runtime:GetQbIdentifier(source, idType)");
    expect(server).toContain("function QBCore.Functions.GetSource(identifier)");
    expect(server).toContain("return exports.sdb_runtime:GetQbSource(identifier)");
    expect(server).toContain("function QBCore.Functions.GetPlayerByCitizenId(citizenid)");
    expect(server).toContain("return exports.sdb_runtime:GetQbPlayerByCitizenId(citizenid)");
    expect(server).toContain("function QBCore.Functions.GetPlayerByPhone(number)");
    expect(server).toContain("return exports.sdb_runtime:GetQbPlayerByPhone(number)");
    expect(server).toContain("function QBCore.Functions.GetPlayerByAccount(account)");
    expect(server).toContain("return exports.sdb_runtime:GetQbPlayerByAccount(account)");
    expect(server).toContain("function QBCore.Functions.GetPlayerByCharInfo(key, value)");
    expect(server).toContain("return exports.sdb_runtime:GetQbPlayerByCharInfo(key, value)");
    expect(server).toContain("function QBCore.Functions.GetPlayersOnDuty(job)");
    expect(server).toContain("return exports.sdb_runtime:GetQbPlayersOnDuty(job)");
    expect(server).toContain("function QBCore.Functions.GetPlayersByJob(job, checkOnDuty)");
    expect(server).toContain("return exports.sdb_runtime:GetQbPlayersByJob(job, checkOnDuty)");
    expect(server).toContain("function QBCore.Functions.GetDutyCount(job)");
    expect(server).toContain("return exports.sdb_runtime:GetQbDutyCount(job)");
    expect(server).toContain("function QBCore.Functions.GetCoords(entity)");
    expect(server).toContain("return vector4(coords.x, coords.y, coords.z, GetEntityHeading(entity))");
    expect(server).toContain("function QBCore.Functions.GetClosestObject(source, coords)");
    expect(server).toContain("return GetClosestEntityFromPool(GetAllObjects(), source, coords)");
    expect(server).toContain("function QBCore.Functions.GetClosestVehicle(source, coords)");
    expect(server).toContain("return GetClosestEntityFromPool(GetAllVehicles(), source, coords)");
    expect(server).toContain("function QBCore.Functions.GetClosestPed(source, coords)");
    expect(server).toContain("return GetClosestEntityFromPool(GetAllPeds(), source, coords, GetPlayerPed(source))");
    expect(server).toContain("function QBCore.Functions.GetBucketObjects()");
    expect(server).toContain("return QBCore.Player_Buckets, QBCore.Entity_Buckets");
    expect(server).toContain("function QBCore.Functions.GetPlayersInBucket(bucket)");
    expect(server).toContain("return QBCore.Player_Buckets[bucket]");
    expect(server).toContain("function QBCore.Functions.GetEntitiesInBucket(bucket)");
    expect(server).toContain("return QBCore.Entity_Buckets[bucket]");
    expect(server).toContain("function QBCore.Functions.SetEntityBucket(entity, bucket)");
    expect(server).toContain("SetEntityRoutingBucket(entity, bucket)");
    expect(server).toContain("function QBCore.Functions.SetPlayerBucket(source, bucket)");
    expect(server).toContain("SetPlayerRoutingBucket(source, bucket)");
    expect(server).toContain("function QBCore.Functions.CreateCallback(name, cb)");
    expect(server).toContain("QBCore.ServerCallbacks[name] = cb");
    expect(server).toContain("function QBCore.Functions.TriggerClientCallback(name, source, ...)");
    expect(server).toContain("QBCore.ClientCallbacks[name .. source] = {");
    expect(server).toContain("TriggerClientEvent('QBCore:Client:TriggerClientCallback', source, name, table.unpack(args))");
    expect(server).toContain("RegisterNetEvent('QBCore:Server:TriggerCallback', function(name, ...)");
    expect(server).toContain("local callback = QBCore.ServerCallbacks[name]");
    expect(server).toContain("TriggerClientEvent('QBCore:Client:TriggerCallback', requestSource, name, ...)");
    expect(server).toContain("RegisterNetEvent('QBCore:Server:TriggerClientCallback', function(name, ...)");
    expect(server).toContain("local pending = QBCore.ClientCallbacks[name .. source]");
    expect(server).toContain("function QBCore.Functions.HasPermission(source, permission)");
    expect(server).toContain("exports.sdb_runtime:HasPermission(source, permission)");
    expect(server).toContain("IsPlayerAceAllowed(source, permission)");
    expect(server).toContain("function QBCore.Functions.GetPermission(source)");
    expect(server).toContain("exports.sdb_runtime:GetPermissions(source)");
    expect(server).toContain("function QBCore.Functions.IsOptIn(source)");
    expect(server).toContain("return QBCore.PlayerOptIns[source] == true");
    expect(server).toContain("function QBCore.Functions.ToggleOptIn(source)");
    expect(server).toContain("QBCore.PlayerOptIns[source] = not QBCore.PlayerOptIns[source]");
    expect(server).toContain("function QBCore.Functions.AddPermission(source, permission)");
    expect(server).toContain("ExecuteCommand(('add_principal player.%s qbcore.%s'):format(source, permission))");
    expect(server).toContain("function QBCore.Functions.RemovePermission(source, permission)");
    expect(server).toContain("ExecuteCommand(('remove_principal player.%s qbcore.%s'):format(source, permission))");
    expect(server).toContain("function QBCore.Commands.Add(name, help, arguments, argsrequired, callback, permission, ...)");
    expect(server).toContain("RegisterCommand(name, function(source, args, rawCommand)");
    expect(server).toContain("if argsrequired and #args < #arguments then");
    expect(server).toContain("callback(source, args, rawCommand)");
    expect(server).toContain("QBCore.Commands.List[name:lower()] = {");
    expect(server).toContain("function QBCore.Commands.Refresh(source)");
    expect(server).toContain("TriggerClientEvent('chat:addSuggestions', source, suggestions)");
    expect(server).toContain("TriggerClientEvent('chat:removeSuggestion', source, '/' .. command)");
    expect(server).toContain("UseableItems = {}");
    expect(server).toContain("function QBCore.Functions.CreateUseableItem(item, data)");
    expect(server).toContain("QBCore.UseableItems[item] = { callback = data }");
    expect(server).toContain("QBCore.UseableItems[item] = data");
    expect(server).toContain("function QBCore.Functions.CanUseItem(item)");
    expect(server).toContain("return useable.callback or useable");
    expect(server).toContain("function QBCore.Functions.HasItem(source, items, amount)");
    expect(server).toContain("return Player.Functions.HasItem(items, requiredAmount)");
    expect(server).toContain("function QBCore.Functions.UseItem(source, item)");
    expect(server).toContain("local itemName = type(item) == 'table' and item.name or item");
    expect(server).toContain("local inventoryItem = Player.Functions.GetItemByName(itemName)");
    expect(server).toContain("callback(source, inventoryItem)");
    expect(server).toContain("RegisterNetEvent('QBCore:Server:UseItem', function(itemName)");
    expect(server).toContain("QBCore.Functions.UseItem(source, itemName)");
    expect(server).toContain("RegisterNetEvent('QBCore:Server:SpawnVehicle', function(model, coords, isnetworked)");
    expect(server).toContain("local function SpawnQbVehicle(source, model, vehType, coords, warp)");
    expect(server).toContain("local ok, spawned = exports.sdb_runtime:SpawnVehicles({");
    expect(server).toContain("vehType = vehType");
    expect(server).toContain("warpIntoVehicle = warp == true");
    expect(server).toContain("return spawned[1] and spawned[1].vehicle or 0");
    expect(server).toContain("function QBCore.Functions.SpawnVehicle(source, model, coords, warp)");
    expect(server).toContain("return SpawnQbVehicle(source, model, nil, coords, warp)");
    expect(server).toContain("function QBCore.Functions.CreateAutomobile(source, model, coords, warp)");
    expect(server).toContain("return SpawnQbVehicle(source, model, 'automobile', coords, warp)");
    expect(server).toContain("function QBCore.Functions.CreateVehicle(source, model, vehType, coords, warp)");
    expect(server).toContain("return SpawnQbVehicle(source, model, vehType, coords, warp)");
    expect(server).toContain("exports.sdb_runtime:SpawnVehicles({");
    expect(server).toContain("targetSource = requestSource");
    expect(server).toContain("model = model");
    expect(server).toContain("location = coords");
    expect(server).toContain("networked = isnetworked ~= false");
    expect(server).toContain("RegisterNetEvent('QBCore:Server:DeleteVehicle', function(vehicleNetId)");
    expect(server).toContain("exports.sdb_runtime:DeleteVehicle(vehicleNetId)");
    expect(server).toContain("function QBCore.Functions.Notify(source, text, textType, length)");
    expect(server).toContain("TriggerClientEvent('QBCore:Notify', source, text, textType or 'primary', length or 5000)");
    expect(server).toContain("function QBCore.Debug(value, indent, resource)");
    expect(server).toContain("print(json.encode(value, { indent = true }))");
    expect(server).toContain("function QBCore.ShowError(resource, message)");
    expect(server).toContain("function QBCore.ShowSuccess(resource, message)");
    expect(server).toContain("function QBCore.Functions.Kick(playerId, reason, setKickReason, deferrals)");
    expect(server).toContain("exports.sdb_runtime:KickPlayer({");
    expect(server).toContain("RegisterNetEvent('QBCore:Shared:Update', function(shared)");
    expect(server).toContain("QBCore.Shared = shared or exports.sdb_runtime:GetQbShared()");
    expect(server).toContain("exports('GetCoreObject', function()");
    expect(server).toContain("return QBCore");
    expect(server).toContain("exports('GetPlayer', function(source)");
    expect(server).toContain("return QBCore.Functions.GetPlayer(source)");
  });

  it("exports the client QBCore object and direct player data getter through sdb_runtime", () => {
    const client = read("resources/[compat]/qb-core/client/main.lua");

    expect(client).toContain("local QBCore = {");
    expect(client).toContain("PlayerData = {}");
    expect(client).toContain("Functions = {}");
    expect(client).toContain("Shared = exports.sdb_runtime:GetQbShared()");
    expect(client).toContain("QBCore.Shared.Items = QBCore.Shared.Items or {}");
    expect(client).toContain("QBCore.Shared.Jobs = QBCore.Shared.Jobs or {}");
    expect(client).toContain("QBCore.Shared.Gangs = QBCore.Shared.Gangs or {}");
    expect(client).toContain("QBCore.Shared.Vehicles = QBCore.Shared.Vehicles or {}");
    expect(client).toContain("QBCore.Shared.Weapons = QBCore.Shared.Weapons or {}");
    expect(client).toContain("QBCore.Shared.StarterItems = QBCore.Shared.StarterItems or {}");
    expect(client).toContain("QBCore.Shared.MoneyTypes = QBCore.Shared.MoneyTypes or { cash = 500, bank = 5000, crypto = 0 }");
    expect(client).toContain("QBCore.Shared.DefaultMetadata = QBCore.Shared.DefaultMetadata or {}");
    expect(client).toContain("ServerCallbacks = {}");
    expect(client).toContain("ClientCallbacks = {}");
    expect(client).toContain("function QBCore.Functions.GetPlayerData(cb)");
    expect(client).toContain("QBCore.PlayerData = exports.sdb_runtime:GetQbPlayerData()");
    expect(client).toContain("if not cb then return QBCore.PlayerData end");
    expect(client).toContain("function QBCore.Functions.GetCoords(entity)");
    expect(client).toContain("return vector4(coords.x, coords.y, coords.z, heading)");
    expect(client).toContain("function QBCore.Functions.Notify(text, textType, length, icon)");
    expect(client).toContain("SendNUIMessage({");
    expect(client).toContain("type = 'QBCore:Notify'");
    expect(client).toContain("function QBCore.Functions.GetShared(name)");
    expect(client).toContain("function QBCore.Functions.DrawText(text, position)");
    expect(client).toContain("action = 'DRAW_TEXT'");
    expect(client).toContain("function QBCore.Functions.HideText()");
    expect(client).toContain("action = 'HIDE_TEXT'");
    expect(client).toContain("function QBCore.Functions.KeyPressed()");
    expect(client).toContain("action = 'KEY_PRESSED'");
    expect(client).toContain("function QBCore.Functions.HasItem(itemName, amount)");
    expect(client).toContain("for _, item in ipairs((QBCore.PlayerData and QBCore.PlayerData.items) or {}) do");
    expect(client).toContain("function QBCore.Functions.Progressbar(name, label, duration, useWhileDead, canCancel, disableControls, animation, prop, propTwo, onFinish, onCancel)");
    expect(client).toContain("exports['progressbar']:Progress(progress, function(cancelled)");
    expect(client).toContain("function QBCore.Functions.GetVehicles()");
    expect(client).toContain("return GetGamePool('CVehicle')");
    expect(client).toContain("function QBCore.Functions.GetPlayers()");
    expect(client).toContain("for _, player in ipairs(GetActivePlayers()) do");
    expect(client).toContain("function QBCore.Functions.GetPeds(ignoreList)");
    expect(client).toContain("for ped in EnumeratePeds() do");
    expect(client).toContain("function QBCore.Functions.GetClosestPed(coords, ignoreList)");
    expect(client).toContain("function QBCore.Functions.GetClosestVehicle(coords)");
    expect(client).toContain("for _, vehicle in ipairs(GetGamePool('CVehicle')) do");
    expect(client).toContain("function QBCore.Functions.GetClosestObject(coords)");
    expect(client).toContain("for _, object in ipairs(GetGamePool('CObject')) do");
    expect(client).toContain("function QBCore.Functions.GetClosestPlayer(coords)");
    expect(client).toContain("function QBCore.Functions.GetPlayersFromCoords(coords, distance)");
    expect(client).toContain("function QBCore.Functions.SpawnVehicle(model, cb, coords, isnetworked)");
    expect(client).toContain("TriggerServerEvent('QBCore:Server:SpawnVehicle', model, coords, isnetworked)");
    expect(client).toContain("function QBCore.Functions.DeleteVehicle(vehicle)");
    expect(client).toContain("TriggerServerEvent('QBCore:Server:DeleteVehicle', VehToNet(vehicle))");
    expect(client).toContain("function QBCore.Functions.GetPlate(vehicle)");
    expect(client).toContain("return QBCore.Shared.Trim(GetVehicleNumberPlateText(vehicle))");
    expect(client).toContain("function QBCore.Functions.GetVehicleProperties(vehicle)");
    expect(client).toContain("model = GetEntityModel(vehicle)");
    expect(client).toContain("function QBCore.Functions.SetVehicleProperties(vehicle, props)");
    expect(client).toContain("SetVehicleNumberPlateText(vehicle, props.plate)");
    expect(client).toContain("function QBCore.Functions.CreateClientCallback(name, cb)");
    expect(client).toContain("QBCore.ClientCallbacks[name] = cb");
    expect(client).toContain("function QBCore.Functions.TriggerCallback(name, ...)");
    expect(client).toContain("QBCore.ServerCallbacks[name] = {");
    expect(client).toContain("TriggerServerEvent('QBCore:Server:TriggerCallback', name, table.unpack(args))");
    expect(client).toContain("RegisterNetEvent('QBCore:Client:TriggerCallback', function(name, ...)");
    expect(client).toContain("local pending = QBCore.ServerCallbacks[name]");
    expect(client).toContain("RegisterNetEvent('QBCore:Client:TriggerClientCallback', function(name, ...)");
    expect(client).toContain("local callback = QBCore.ClientCallbacks[name]");
    expect(client).toContain("TriggerServerEvent('QBCore:Server:TriggerClientCallback', name, ...)");
    expect(client).toContain("RegisterNetEvent('QBCore:Player:SetPlayerData', function(playerData)");
    expect(client).toContain("QBCore.PlayerData = playerData or {}");
    expect(client).toContain("RegisterNetEvent('QBCore:Client:OnPlayerUnload', function()");
    expect(client).toContain("RegisterNetEvent('QBCore:Shared:Update', function(shared)");
    expect(client).toContain("QBCore.Shared = shared or exports.sdb_runtime:GetQbShared()");
    expect(client).toContain("exports('GetCoreObject', function()");
    expect(client).toContain("exports('GetPlayerData', function()");
    expect(client).toContain("exports('GetShared', function(name)");
    expect(client).toContain("exports('DrawText', function(text, position)");
    expect(client).toContain("exports('HideText', function()");
    expect(client).toContain("exports('KeyPressed', function()");
  });

  it("adds runtime exports used by the compatibility facade", () => {
    const server = read("resources/[runtime]/sdb_runtime/server/main.lua");
    const client = read("resources/[runtime]/sdb_runtime/client/main.lua");

    expect(server).toContain("qbPlayers = {}");
    expect(server).toContain("qbShared = {");
    expect(server).toContain("Items = {}");
    expect(server).toContain("Jobs = {}");
    expect(server).toContain("Gangs = {}");
    expect(server).toContain("Vehicles = {}");
    expect(server).toContain("Weapons = {}");
    expect(server).toContain("StarterItems = {}");
    expect(server).toContain("MoneyTypes = { cash = 500, bank = 5000, crypto = 0 }");
    expect(server).toContain("DefaultMetadata = {}");
    expect(server).toContain("qbCharacterSelections = {}");
    expect(server).toContain("local function GetQbPlayer(source)");
    expect(server).toContain("local function UpsertQbPlayer(source, playerData)");
    expect(server).toContain("local function QueueQbCharacterSelection(source, characterId)");
    expect(server).toContain("if IsBlankString(characterId) then");
    expect(server).toContain("Runtime.qbCharacterSelections[#Runtime.qbCharacterSelections + 1] = selection");
    expect(server).toContain("local function DrainQbCharacterSelections()");
    expect(server).toContain("function SelectQbCharacter(source, characterId, playerData)");
    expect(server).toContain("Runtime.qbPlayers[target] = player");
    expect(server).toContain("QueueQbCharacterSelection(target, characterId)");
    expect(server).toContain("local function BuildDefaultQbPlayerData(target)");
    expect(server).toContain("PlayerData = nextPlayerData");
    expect(server).toContain("position = {");
    expect(server).toContain("TriggerClientEvent('QBCore:Client:OnPlayerLoaded', target)");
    expect(server).toContain("TriggerClientEvent('QBCore:Player:SetPlayerData', target, player.PlayerData)");
    expect(server).toContain("AddEventHandler('playerDropped', function()");
    expect(server).toContain("Runtime.qbPlayers[source] = nil");
    expect(server).toContain("Functions = {");
    expect(server).toContain("exports('GetQbPlayer', GetQbPlayer)");
    expect(server).toContain("exports('UpsertQbPlayer', UpsertQbPlayer)");
    expect(server).toContain("exports('SelectQbCharacter', SelectQbCharacter)");
    expect(server).toContain("exports('DrainQbCharacterSelections', DrainQbCharacterSelections)");
    expect(server).toContain("local function GetQbPlayers()");
    expect(server).toContain("return Runtime.qbPlayers");
    expect(server).toContain("exports('GetQbPlayers', GetQbPlayers)");
    expect(server).toContain("local function GetQbPlayerSources()");
    expect(server).toContain("exports('GetQbPlayerSources', GetQbPlayerSources)");
    expect(server).toContain("local function GetQbIdentifier(source, idType)");
    expect(server).toContain("local function GetQbSource(identifier)");
    expect(server).toContain("local function GetQbPlayerByCitizenId(citizenid)");
    expect(server).toContain("local function GetQbPlayerByPhone(number)");
    expect(server).toContain("local function GetQbPlayerByAccount(account)");
    expect(server).toContain("local function GetQbPlayerByCharInfo(key, value)");
    expect(server).toContain("if IsBlankString(identifier) then");
    expect(server).toContain("if IsBlankString(citizenid) then");
    expect(server).toContain("if IsBlankString(number) then");
    expect(server).toContain("if IsBlankString(account) then");
    expect(server).toContain("if IsBlankString(key) then");
    expect(server).toContain("local function GetQbPlayersOnDuty(job)");
    expect(server).toContain("if IsBlankString(job) then");
    expect(server).toContain("local function GetQbPlayersByJob(job, checkOnDuty)");
    expect(server).toContain("if playerJob.name == job or playerJob.type == job then");
    expect(server).toContain("local function GetQbDutyCount(job)");
    expect(server).toContain("local function GetQbShared()");
    expect(server).toContain("local function SyncQbShared(shared)");
    expect(server).toContain("Runtime.qbShared.Items = shared.items or shared.Items or Runtime.qbShared.Items");
    expect(server).toContain("Runtime.qbShared.Weapons = shared.weapons or shared.Weapons or Runtime.qbShared.Weapons");
    expect(server).toContain("TriggerClientEvent('QBCore:Shared:Update', -1, Runtime.qbShared)");
    expect(server).toContain("local function GetPermissions(source)");
    expect(server).toContain("return principalPermissions");
    expect(server).toContain("local function DeleteVehicle(vehicleNetId)");
    expect(server).toContain("local entity = NetworkGetEntityFromNetworkId(netId)");
    expect(server).toContain("DeleteEntity(entity)");
    expect(server).toContain("exports('GetQbIdentifier', GetQbIdentifier)");
    expect(server).toContain("exports('GetQbSource', GetQbSource)");
    expect(server).toContain("exports('GetQbPlayerByCitizenId', GetQbPlayerByCitizenId)");
    expect(server).toContain("exports('GetQbPlayerByPhone', GetQbPlayerByPhone)");
    expect(server).toContain("exports('GetQbPlayerByAccount', GetQbPlayerByAccount)");
    expect(server).toContain("exports('GetQbPlayerByCharInfo', GetQbPlayerByCharInfo)");
    expect(server).toContain("exports('GetQbPlayersOnDuty', GetQbPlayersOnDuty)");
    expect(server).toContain("exports('GetQbPlayersByJob', GetQbPlayersByJob)");
    expect(server).toContain("exports('GetQbDutyCount', GetQbDutyCount)");
    expect(server).toContain("exports('GetQbShared', GetQbShared)");
    expect(server).toContain("exports('SyncQbShared', SyncQbShared)");
    expect(server).toContain("exports('GetPermissions', GetPermissions)");
    expect(server).toContain("exports('DeleteVehicle', DeleteVehicle)");
    expect(client).toContain("local function GetQbPlayerData()");
    expect(client).toContain("local function GetQbShared()");
    expect(client).toContain("RegisterNetEvent('QBCore:Shared:Update', function(shared)");
    expect(client).toContain("local QbPlayerData = {}");
    expect(client).toContain("RegisterNetEvent('QBCore:Player:SetPlayerData', function(playerData)");
    expect(client).toContain("QbPlayerData = playerData or {}");
    expect(client).toContain("RegisterNetEvent('QBCore:Client:OnPlayerUnload', function()");
    expect(client).toContain("QbPlayerData = {}");
    expect(client).toContain("exports('GetQbPlayerData', GetQbPlayerData)");
    expect(client).toContain("exports('GetQbShared', GetQbShared)");
  });

  it("syncs authoritative QBCore PlayerData snapshots through a trusted runtime event", () => {
    const server = read("resources/[runtime]/sdb_runtime/server/main.lua");

    expect(server).toContain("local function SyncQbPlayerData(players)");
    expect(server).toContain("if type(players) ~= 'table' then");
    expect(server).toContain("return false, 'QBCore player sync requires players table'");
    expect(server).toContain("local previous = Runtime.qbPlayers[target]");
    expect(server).toContain("local player = UpsertQbPlayer(target, playerData)");
    expect(server).toContain("EmitQbPlayerDeltaEvents(target, previous and previous.PlayerData or nil, player.PlayerData)");
    expect(server).toContain("TriggerClientEvent('QBCore:Client:OnMoneyChange', target");
    expect(server).toContain("TriggerClientEvent('QBCore:Client:OnJobUpdate', target, nextData.job)");
    expect(server).toContain("TriggerClientEvent('QBCore:Client:OnGangUpdate', target, nextData.gang)");
    expect(server).toContain("TriggerClientEvent('QBCore:Client:OnMetaDataUpdate', target, nextData.metadata)");
    expect(server).toContain("RegisterNetEvent('sdb_runtime:syncQbPlayerData', function(players)");
    expect(server).toContain("if source ~= 0 then");
    expect(server).toContain("DispatchRuntimeEvent('sdb_runtime:syncQbPlayerData'");
    expect(server).toContain("if eventName == 'sdb_runtime:syncQbPlayerData' then");
    expect(server).toContain("return SyncQbPlayerData(payload.players or payload)");
    expect(server).toContain("exports('SyncQbPlayerData', SyncQbPlayerData)");
  });

  it("queues runtime-originated QBCore character updates from player methods", () => {
    const server = read("resources/[runtime]/sdb_runtime/server/main.lua");

    expect(server).toContain("qbCharacterUpdates = {}");
    expect(server).toContain("local function QueueQbCharacterUpdate(source, playerData)");
    expect(server).toContain("characterId = playerData.characterId or playerData.citizenid");
    expect(server).toContain("if IsBlankString(update.characterId) then");
    expect(server).toContain("if IsBlankString(update.citizenId) then");
    expect(server).toContain("playerPrincipalId = ('player:%s'):format(target)");
    expect(server).toContain("charinfoJson = json.encode(playerData.charinfo or {})");
    expect(server).toContain("metadataJson = json.encode(playerData.metadata or {})");
    expect(server).toContain("gangJson = json.encode(playerData.gang or {})");
    expect(server).toContain("positionJson = json.encode(playerData.position or {})");
    expect(server).toContain("Runtime.qbCharacterUpdates[#Runtime.qbCharacterUpdates + 1] = update");
    expect(server).toContain("local function DrainQbCharacterUpdates()");
    expect(server).toContain("Runtime.qbCharacterUpdates = {}");
    expect(server).toContain("local function RefreshQbPlayerPosition(player)");
    expect(server).toContain("local ped = GetPlayerPed(player.PlayerData.source)");
    expect(server).toContain("local coords = GetEntityCoords(ped)");
    expect(server).toContain("w = GetEntityHeading(ped)");
    expect(server).toContain("function player.Functions.UpdatePlayerData()");
    expect(server).toContain("function player.Functions.SetPlayerData(key, value)");
    expect(server).toContain("if IsBlankString(key) then");
    expect(server).toContain("function player.Functions.SetMetaData(key, value)");
    expect(server).toContain("function player.Functions.GetMetaData(key)");
    expect(server).toContain("function player.Functions.SetJob(jobName, grade)");
    expect(server).toContain("if IsBlankString(jobName) then");
    expect(server).toContain("function player.Functions.SetJobDuty(onDuty)");
    expect(server).toContain("function player.Functions.SetGang(gangName, grade)");
    expect(server).toContain("if IsBlankString(gangName) then");
    expect(server).toContain("function player.Functions.Save()");
    expect(server).toContain("function player.Functions.Logout()");
    expect(server).toContain("function player.Functions.AddMethod(methodName, handler)");
    expect(server).toContain("if IsBlankString(methodName) then");
    expect(server).toContain("function player.Functions.AddField(fieldName, value)");
    expect(server).toContain("if IsBlankString(fieldName) then");
    expect(server).toContain("player.Functions[methodName] = handler");
    expect(server).toContain("player[fieldName] = value");
    expect(server).toContain("player.SetMetaData = player.Functions.SetMetaData");
    expect(server).toContain("player.GetMetaData = player.Functions.GetMetaData");
    expect(server).toContain("player.SetPlayerData = player.Functions.SetPlayerData");
    expect(server).toContain("player.UpdatePlayerData = player.Functions.UpdatePlayerData");
    expect(server).toContain("player.AddMoney = player.Functions.AddMoney");
    expect(server).toContain("player.AddItem = player.Functions.AddItem");
    expect(server).toContain("RefreshQbPlayerPosition(player)");
    expect(server).toContain("QueueQbCharacterUpdate(player.PlayerData.source, player.PlayerData)");
    expect(server).toContain("TriggerClientEvent('QBCore:Client:OnJobUpdate', player.PlayerData.source, player.PlayerData.job)");
    expect(server).toContain("Runtime.qbPlayers[player.PlayerData.source] = nil");
    expect(server).toContain("TriggerClientEvent('QBCore:Client:OnPlayerUnload', player.PlayerData.source)");
    expect(server).toContain("TriggerClientEvent('QBCore:Client:OnGangUpdate', player.PlayerData.source, player.PlayerData.gang)");
    expect(server).toContain("exports('QueueQbCharacterUpdate', QueueQbCharacterUpdate)");
    expect(server).toContain("exports('DrainQbCharacterUpdates', DrainQbCharacterUpdates)");
  });

  it("queues QBCore money method updates for ledger-backed persistence", () => {
    const server = read("resources/[runtime]/sdb_runtime/server/main.lua");

    expect(server).toContain("qbMoneyUpdates = {}");
    expect(server).toContain("local function IsBlankString(value)");
    expect(server).toContain("local function QueueQbMoneyUpdate(source, moneyType, operation, amount, reason)");
    expect(server).toContain("if IsBlankString(moneyType) then");
    expect(server).toContain("if IsBlankString(characterId) then");
    expect(server).toContain("operation = operation");
    expect(server).toContain("Runtime.qbMoneyUpdates[#Runtime.qbMoneyUpdates + 1] = update");
    expect(server).toContain("local function DrainQbMoneyUpdates()");
    expect(server).toContain("Runtime.qbMoneyUpdates = {}");
    expect(server).toContain("function player.Functions.AddMoney(moneyType, amount, reason)");
    expect(server).toContain("function player.Functions.RemoveMoney(moneyType, amount, reason)");
    expect(server).toContain("function player.Functions.SetMoney(moneyType, amount, reason)");
    expect(server).toContain("QueueQbMoneyUpdate(player.PlayerData.source, moneyType, 'add', amount, reason)");
    expect(server).toContain("QueueQbMoneyUpdate(player.PlayerData.source, moneyType, 'remove', amount, reason)");
    expect(server).toContain("QueueQbMoneyUpdate(player.PlayerData.source, moneyType, 'set', amount, reason)");
    expect(server).toContain("TriggerClientEvent('QBCore:Client:OnMoneyChange', player.PlayerData.source, player.PlayerData.money)");
    expect(server).toContain("exports('DrainQbMoneyUpdates', DrainQbMoneyUpdates)");
  });

  it("queues QBCore inventory method updates for gameplay-backed persistence", () => {
    const server = read("resources/[runtime]/sdb_runtime/server/main.lua");

    expect(server).toContain("qbInventoryUpdates = {}");
    expect(server).toContain("local function QueueQbInventoryUpdate(source, itemKey, operation, amount)");
    expect(server).toContain("if IsBlankString(itemKey) then");
    expect(server).toContain("if IsBlankString(characterId) then");
    expect(server).toContain("operation = operation");
    expect(server).toContain("Runtime.qbInventoryUpdates[#Runtime.qbInventoryUpdates + 1] = update");
    expect(server).toContain("local function DrainQbInventoryUpdates()");
    expect(server).toContain("Runtime.qbInventoryUpdates = {}");
    expect(server).toContain("function player.Functions.AddItem(itemKey, amount, slot, info)");
    expect(server).toContain("function player.Functions.RemoveItem(itemKey, amount)");
    expect(server).toContain("function player.Functions.GetItemByName(itemKey)");
    expect(server).toContain("function player.Functions.HasItem(itemKey, amount)");
    expect(server).toContain("QueueQbInventoryUpdate(player.PlayerData.source, itemKey, 'add', amount)");
    expect(server).toContain("QueueQbInventoryUpdate(player.PlayerData.source, itemKey, 'remove', amount)");
    expect(server).toContain("exports('DrainQbInventoryUpdates', DrainQbInventoryUpdates)");
  });
});
