// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  serverId: __t.string().name("server_id"),
  actorId: __t.string().name("actor_id"),
  pluginId: __t.string().name("plugin_id"),
  actionType: __t.string().name("action_type"),
  permissionKey: __t.string().name("permission_key"),
  targetType: __t.string().name("target_type"),
  targetId: __t.string().name("target_id"),
  beforeJson: __t.string().name("before_json"),
  afterJson: __t.string().name("after_json"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
