// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  playerPrincipalId: __t.string().name("player_principal_id"),
  citizenId: __t.string().name("citizen_id"),
  cid: __t.u64(),
  slot: __t.u64(),
  license: __t.string(),
  name: __t.string(),
  charinfoJson: __t.string().name("charinfo_json"),
  metadataJson: __t.string().name("metadata_json"),
  gangJson: __t.string().name("gang_json"),
  positionJson: __t.string().name("position_json"),
  phoneNumber: __t.string().name("phone_number"),
  accountNumber: __t.string().name("account_number"),
  selected: __t.bool(),
  updatedAt: __t.timestamp().name("updated_at"),
});
