// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  transactionId: __t.string(),
  actorId: __t.string(),
  payerAccountId: __t.string(),
  governmentAccountId: __t.string(),
  amount: __t.i128(),
  reason: __t.string(),
  idempotencyKey: __t.string(),
};
