// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.2.0 (commit eb11e2f5c41dce6979715ad407996270d61329f6).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AckConfigVersionReducer from "./ack_config_version_reducer.js";
import AckPermissionCacheVersionReducer from "./ack_permission_cache_version_reducer.js";
import AddPrincipalEdgeReducer from "./add_principal_edge_reducer.js";
import AdminAdjustBalanceReducer from "./admin_adjust_balance_reducer.js";
import AssignJobReducer from "./assign_job_reducer.js";
import BusinessPayoutReducer from "./business_payout_reducer.js";
import BuyItemReducer from "./buy_item_reducer.js";
import ChargeTaxReducer from "./charge_tax_reducer.js";
import CloseMenuSessionReducer from "./close_menu_session_reducer.js";
import CompleteActionReducer from "./complete_action_reducer.js";
import CreateAccountReducer from "./create_account_reducer.js";
import DepositCashReducer from "./deposit_cash_reducer.js";
import FinePlayerReducer from "./fine_player_reducer.js";
import GrantItemReducer from "./grant_item_reducer.js";
import GrantPermissionReducer from "./grant_permission_reducer.js";
import HeartbeatReducer from "./heartbeat_reducer.js";
import IssueInvoiceReducer from "./issue_invoice_reducer.js";
import OpenMenuSessionReducer from "./open_menu_session_reducer.js";
import PayInvoiceReducer from "./pay_invoice_reducer.js";
import PaySalaryReducer from "./pay_salary_reducer.js";
import RecordPluginSandboxEventReducer from "./record_plugin_sandbox_event_reducer.js";
import RegisterItemReducer from "./register_item_reducer.js";
import RegisterJobReducer from "./register_job_reducer.js";
import RegisterLocationReducer from "./register_location_reducer.js";
import RegisterPermissionReducer from "./register_permission_reducer.js";
import RegisterPluginReducer from "./register_plugin_reducer.js";
import RegisterPluginBundleReducer from "./register_plugin_bundle_reducer.js";
import RegisterPluginHookReducer from "./register_plugin_hook_reducer.js";
import RegisterPluginManifestReducer from "./register_plugin_manifest_reducer.js";
import RegisterPluginPackageReducer from "./register_plugin_package_reducer.js";
import RegisterPluginSchemaReducer from "./register_plugin_schema_reducer.js";
import RegisterServerReducer from "./register_server_reducer.js";
import RegisterVehicleReducer from "./register_vehicle_reducer.js";
import RemoveItemReducer from "./remove_item_reducer.js";
import RemovePolicyConstraintReducer from "./remove_policy_constraint_reducer.js";
import RemovePrincipalEdgeReducer from "./remove_principal_edge_reducer.js";
import RevokePackageSignerReducer from "./revoke_package_signer_reducer.js";
import RevokePluginBundleReducer from "./revoke_plugin_bundle_reducer.js";
import SellItemReducer from "./sell_item_reducer.js";
import SetPluginConfigValueReducer from "./set_plugin_config_value_reducer.js";
import SetPluginHooksEnabledReducer from "./set_plugin_hooks_enabled_reducer.js";
import SetPluginStatusReducer from "./set_plugin_status_reducer.js";
import SetRuntimeConfigReducer from "./set_runtime_config_reducer.js";
import SubmitActionReducer from "./submit_action_reducer.js";
import TransferMoneyReducer from "./transfer_money_reducer.js";
import UninstallPluginReducer from "./uninstall_plugin_reducer.js";
import UpsertAceMirrorRuleReducer from "./upsert_ace_mirror_rule_reducer.js";
import UpsertCharacterReducer from "./upsert_character_reducer.js";
import UpsertEconomyLimitReducer from "./upsert_economy_limit_reducer.js";
import UpsertMenuActionReducer from "./upsert_menu_action_reducer.js";
import UpsertMenuDefinitionReducer from "./upsert_menu_definition_reducer.js";
import UpsertMenuVisibilityPolicyReducer from "./upsert_menu_visibility_policy_reducer.js";
import UpsertPluginCapabilityReducer from "./upsert_plugin_capability_reducer.js";
import UpsertPluginDeploymentReducer from "./upsert_plugin_deployment_reducer.js";
import UpsertPluginEntityReducer from "./upsert_plugin_entity_reducer.js";
import UpsertPluginRuntimeInstanceReducer from "./upsert_plugin_runtime_instance_reducer.js";
import UpsertPolicyConstraintReducer from "./upsert_policy_constraint_reducer.js";
import UpsertPrincipalReducer from "./upsert_principal_reducer.js";
import UpsertRuntimeCommandReducer from "./upsert_runtime_command_reducer.js";
import UpsertRuntimePanelReducer from "./upsert_runtime_panel_reducer.js";
import VoidTransactionReducer from "./void_transaction_reducer.js";
import WithdrawCashReducer from "./withdraw_cash_reducer.js";
import WriteAuditLogReducer from "./write_audit_log_reducer.js";

// Import all procedure arg schemas

// Import all table schema definitions
import AccountsRow from "./accounts_table.js";
import AceMirrorRulesRow from "./ace_mirror_rules_table.js";
import AuditLogsRow from "./audit_logs_table.js";
import CharacterJobsRow from "./character_jobs_table.js";
import CharactersRow from "./characters_table.js";
import EconomyLimitsRow from "./economy_limits_table.js";
import InventoryStacksRow from "./inventory_stacks_table.js";
import InvoicesRow from "./invoices_table.js";
import ItemsRow from "./items_table.js";
import JobsRow from "./jobs_table.js";
import LedgerEntriesRow from "./ledger_entries_table.js";
import LocationsRow from "./locations_table.js";
import MenuActionsRow from "./menu_actions_table.js";
import MenuDefinitionsRow from "./menu_definitions_table.js";
import MenuSessionsRow from "./menu_sessions_table.js";
import MenuVisibilityPoliciesRow from "./menu_visibility_policies_table.js";
import PermissionCacheVersionsRow from "./permission_cache_versions_table.js";
import PermissionGrantsRow from "./permission_grants_table.js";
import PermissionsRow from "./permissions_table.js";
import PluginBundlesRow from "./plugin_bundles_table.js";
import PluginCapabilitiesRow from "./plugin_capabilities_table.js";
import PluginConfigValuesRow from "./plugin_config_values_table.js";
import PluginDeploymentsRow from "./plugin_deployments_table.js";
import PluginEntitiesRow from "./plugin_entities_table.js";
import PluginHooksRow from "./plugin_hooks_table.js";
import PluginManifestsRow from "./plugin_manifests_table.js";
import PluginPackageSignerRevocationsRow from "./plugin_package_signer_revocations_table.js";
import PluginPackagesRow from "./plugin_packages_table.js";
import PluginRuntimeInstancesRow from "./plugin_runtime_instances_table.js";
import PluginSandboxEventsRow from "./plugin_sandbox_events_table.js";
import PluginSchemasRow from "./plugin_schemas_table.js";
import PluginsRow from "./plugins_table.js";
import PolicyConstraintsRow from "./policy_constraints_table.js";
import PrincipalEdgesRow from "./principal_edges_table.js";
import PrincipalsRow from "./principals_table.js";
import RuntimeCommandsRow from "./runtime_commands_table.js";
import RuntimeConfigRow from "./runtime_config_table.js";
import RuntimeConfigAcksRow from "./runtime_config_acks_table.js";
import RuntimeInstancesRow from "./runtime_instances_table.js";
import RuntimePanelsRow from "./runtime_panels_table.js";
import ServersRow from "./servers_table.js";
import TransactionsRow from "./transactions_table.js";
import VehiclesRow from "./vehicles_table.js";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  accounts: __table({
    name: 'accounts',
    indexes: [
      { accessor: 'id', name: 'accounts_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'accounts_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AccountsRow),
  ace_mirror_rules: __table({
    name: 'ace_mirror_rules',
    indexes: [
      { accessor: 'id', name: 'ace_mirror_rules_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'ace_mirror_rules_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AceMirrorRulesRow),
  audit_logs: __table({
    name: 'audit_logs',
    indexes: [
      { accessor: 'id', name: 'audit_logs_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'audit_logs_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AuditLogsRow),
  character_jobs: __table({
    name: 'character_jobs',
    indexes: [
      { accessor: 'character_id', name: 'character_jobs_character_id_idx_btree', algorithm: 'btree', columns: [
        'characterId',
      ] },
    ],
    constraints: [
      { name: 'character_jobs_character_id_key', constraint: 'unique', columns: ['characterId'] },
    ],
  }, CharacterJobsRow),
  characters: __table({
    name: 'characters',
    indexes: [
      { accessor: 'id', name: 'characters_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'characters_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharactersRow),
  economy_limits: __table({
    name: 'economy_limits',
    indexes: [
      { accessor: 'id', name: 'economy_limits_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'economy_limits_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EconomyLimitsRow),
  inventory_stacks: __table({
    name: 'inventory_stacks',
    indexes: [
      { accessor: 'id', name: 'inventory_stacks_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'inventory_stacks_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InventoryStacksRow),
  invoices: __table({
    name: 'invoices',
    indexes: [
      { accessor: 'id', name: 'invoices_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'invoices_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InvoicesRow),
  items: __table({
    name: 'items',
    indexes: [
      { accessor: 'key', name: 'items_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'items_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, ItemsRow),
  jobs: __table({
    name: 'jobs',
    indexes: [
      { accessor: 'key', name: 'jobs_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'jobs_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, JobsRow),
  ledger_entries: __table({
    name: 'ledger_entries',
    indexes: [
      { accessor: 'id', name: 'ledger_entries_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'ledger_entries_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LedgerEntriesRow),
  locations: __table({
    name: 'locations',
    indexes: [
      { accessor: 'key', name: 'locations_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'locations_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, LocationsRow),
  menu_actions: __table({
    name: 'menu_actions',
    indexes: [
      { accessor: 'id', name: 'menu_actions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'menu_actions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MenuActionsRow),
  menu_definitions: __table({
    name: 'menu_definitions',
    indexes: [
      { accessor: 'id', name: 'menu_definitions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'menu_definitions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MenuDefinitionsRow),
  menu_sessions: __table({
    name: 'menu_sessions',
    indexes: [
      { accessor: 'id', name: 'menu_sessions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'menu_sessions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MenuSessionsRow),
  menu_visibility_policies: __table({
    name: 'menu_visibility_policies',
    indexes: [
      { accessor: 'id', name: 'menu_visibility_policies_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'menu_visibility_policies_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MenuVisibilityPoliciesRow),
  permission_cache_versions: __table({
    name: 'permission_cache_versions',
    indexes: [
      { accessor: 'server_id', name: 'permission_cache_versions_server_id_idx_btree', algorithm: 'btree', columns: [
        'serverId',
      ] },
    ],
    constraints: [
      { name: 'permission_cache_versions_server_id_key', constraint: 'unique', columns: ['serverId'] },
    ],
  }, PermissionCacheVersionsRow),
  permission_grants: __table({
    name: 'permission_grants',
    indexes: [
      { accessor: 'id', name: 'permission_grants_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'permission_grants_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PermissionGrantsRow),
  permissions: __table({
    name: 'permissions',
    indexes: [
      { accessor: 'id', name: 'permissions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'key', name: 'permissions_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'permissions_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'permissions_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, PermissionsRow),
  plugin_bundles: __table({
    name: 'plugin_bundles',
    indexes: [
      { accessor: 'id', name: 'plugin_bundles_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'plugin_bundles_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PluginBundlesRow),
  plugin_capabilities: __table({
    name: 'plugin_capabilities',
    indexes: [
      { accessor: 'id', name: 'plugin_capabilities_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'plugin_capabilities_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PluginCapabilitiesRow),
  plugin_config_values: __table({
    name: 'plugin_config_values',
    indexes: [
      { accessor: 'id', name: 'plugin_config_values_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'plugin_config_values_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PluginConfigValuesRow),
  plugin_deployments: __table({
    name: 'plugin_deployments',
    indexes: [
      { accessor: 'id', name: 'plugin_deployments_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'plugin_deployments_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PluginDeploymentsRow),
  plugin_entities: __table({
    name: 'plugin_entities',
    indexes: [
      { accessor: 'id', name: 'plugin_entities_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'plugin_entities_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PluginEntitiesRow),
  plugin_hooks: __table({
    name: 'plugin_hooks',
    indexes: [
      { accessor: 'id', name: 'plugin_hooks_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'plugin_hooks_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PluginHooksRow),
  plugin_manifests: __table({
    name: 'plugin_manifests',
    indexes: [
      { accessor: 'plugin_id', name: 'plugin_manifests_plugin_id_idx_btree', algorithm: 'btree', columns: [
        'pluginId',
      ] },
    ],
    constraints: [
      { name: 'plugin_manifests_plugin_id_key', constraint: 'unique', columns: ['pluginId'] },
    ],
  }, PluginManifestsRow),
  plugin_package_signer_revocations: __table({
    name: 'plugin_package_signer_revocations',
    indexes: [
      { accessor: 'signer_id', name: 'plugin_package_signer_revocations_signer_id_idx_btree', algorithm: 'btree', columns: [
        'signerId',
      ] },
    ],
    constraints: [
      { name: 'plugin_package_signer_revocations_signer_id_key', constraint: 'unique', columns: ['signerId'] },
    ],
  }, PluginPackageSignerRevocationsRow),
  plugin_packages: __table({
    name: 'plugin_packages',
    indexes: [
      { accessor: 'package_id', name: 'plugin_packages_package_id_idx_btree', algorithm: 'btree', columns: [
        'packageId',
      ] },
    ],
    constraints: [
      { name: 'plugin_packages_package_id_key', constraint: 'unique', columns: ['packageId'] },
    ],
  }, PluginPackagesRow),
  plugin_runtime_instances: __table({
    name: 'plugin_runtime_instances',
    indexes: [
      { accessor: 'id', name: 'plugin_runtime_instances_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'plugin_runtime_instances_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PluginRuntimeInstancesRow),
  plugin_sandbox_events: __table({
    name: 'plugin_sandbox_events',
    indexes: [
      { accessor: 'id', name: 'plugin_sandbox_events_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'plugin_sandbox_events_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PluginSandboxEventsRow),
  plugin_schemas: __table({
    name: 'plugin_schemas',
    indexes: [
      { accessor: 'id', name: 'plugin_schemas_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'plugin_schemas_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PluginSchemasRow),
  plugins: __table({
    name: 'plugins',
    indexes: [
      { accessor: 'id', name: 'plugins_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'plugins_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PluginsRow),
  policy_constraints: __table({
    name: 'policy_constraints',
    indexes: [
      { accessor: 'id', name: 'policy_constraints_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'policy_constraints_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PolicyConstraintsRow),
  principal_edges: __table({
    name: 'principal_edges',
    indexes: [
      { accessor: 'id', name: 'principal_edges_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'principal_edges_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PrincipalEdgesRow),
  principals: __table({
    name: 'principals',
    indexes: [
      { accessor: 'id', name: 'principals_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'principals_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PrincipalsRow),
  runtime_commands: __table({
    name: 'runtime_commands',
    indexes: [
      { accessor: 'id', name: 'runtime_commands_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'runtime_commands_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RuntimeCommandsRow),
  runtime_config: __table({
    name: 'runtime_config',
    indexes: [
      { accessor: 'id', name: 'runtime_config_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'runtime_config_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RuntimeConfigRow),
  runtime_config_acks: __table({
    name: 'runtime_config_acks',
    indexes: [
      { accessor: 'id', name: 'runtime_config_acks_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'runtime_config_acks_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RuntimeConfigAcksRow),
  runtime_instances: __table({
    name: 'runtime_instances',
    indexes: [
      { accessor: 'id', name: 'runtime_instances_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'runtime_instances_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RuntimeInstancesRow),
  runtime_panels: __table({
    name: 'runtime_panels',
    indexes: [
      { accessor: 'id', name: 'runtime_panels_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'runtime_panels_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RuntimePanelsRow),
  servers: __table({
    name: 'servers',
    indexes: [
      { accessor: 'id', name: 'servers_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'servers_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ServersRow),
  transactions: __table({
    name: 'transactions',
    indexes: [
      { accessor: 'id', name: 'transactions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'transactions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TransactionsRow),
  vehicles: __table({
    name: 'vehicles',
    indexes: [
      { accessor: 'model', name: 'vehicles_model_idx_btree', algorithm: 'btree', columns: [
        'model',
      ] },
    ],
    constraints: [
      { name: 'vehicles_model_key', constraint: 'unique', columns: ['model'] },
    ],
  }, VehiclesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("ack_config_version", AckConfigVersionReducer),
  __reducerSchema("ack_permission_cache_version", AckPermissionCacheVersionReducer),
  __reducerSchema("add_principal_edge", AddPrincipalEdgeReducer),
  __reducerSchema("admin_adjust_balance", AdminAdjustBalanceReducer),
  __reducerSchema("assign_job", AssignJobReducer),
  __reducerSchema("business_payout", BusinessPayoutReducer),
  __reducerSchema("buy_item", BuyItemReducer),
  __reducerSchema("charge_tax", ChargeTaxReducer),
  __reducerSchema("close_menu_session", CloseMenuSessionReducer),
  __reducerSchema("complete_action", CompleteActionReducer),
  __reducerSchema("create_account", CreateAccountReducer),
  __reducerSchema("deposit_cash", DepositCashReducer),
  __reducerSchema("fine_player", FinePlayerReducer),
  __reducerSchema("grant_item", GrantItemReducer),
  __reducerSchema("grant_permission", GrantPermissionReducer),
  __reducerSchema("heartbeat", HeartbeatReducer),
  __reducerSchema("issue_invoice", IssueInvoiceReducer),
  __reducerSchema("open_menu_session", OpenMenuSessionReducer),
  __reducerSchema("pay_invoice", PayInvoiceReducer),
  __reducerSchema("pay_salary", PaySalaryReducer),
  __reducerSchema("record_plugin_sandbox_event", RecordPluginSandboxEventReducer),
  __reducerSchema("register_item", RegisterItemReducer),
  __reducerSchema("register_job", RegisterJobReducer),
  __reducerSchema("register_location", RegisterLocationReducer),
  __reducerSchema("register_permission", RegisterPermissionReducer),
  __reducerSchema("register_plugin", RegisterPluginReducer),
  __reducerSchema("register_plugin_bundle", RegisterPluginBundleReducer),
  __reducerSchema("register_plugin_hook", RegisterPluginHookReducer),
  __reducerSchema("register_plugin_manifest", RegisterPluginManifestReducer),
  __reducerSchema("register_plugin_package", RegisterPluginPackageReducer),
  __reducerSchema("register_plugin_schema", RegisterPluginSchemaReducer),
  __reducerSchema("register_server", RegisterServerReducer),
  __reducerSchema("register_vehicle", RegisterVehicleReducer),
  __reducerSchema("remove_item", RemoveItemReducer),
  __reducerSchema("remove_policy_constraint", RemovePolicyConstraintReducer),
  __reducerSchema("remove_principal_edge", RemovePrincipalEdgeReducer),
  __reducerSchema("revoke_package_signer", RevokePackageSignerReducer),
  __reducerSchema("revoke_plugin_bundle", RevokePluginBundleReducer),
  __reducerSchema("sell_item", SellItemReducer),
  __reducerSchema("set_plugin_config_value", SetPluginConfigValueReducer),
  __reducerSchema("set_plugin_hooks_enabled", SetPluginHooksEnabledReducer),
  __reducerSchema("set_plugin_status", SetPluginStatusReducer),
  __reducerSchema("set_runtime_config", SetRuntimeConfigReducer),
  __reducerSchema("submit_action", SubmitActionReducer),
  __reducerSchema("transfer_money", TransferMoneyReducer),
  __reducerSchema("uninstall_plugin", UninstallPluginReducer),
  __reducerSchema("upsert_ace_mirror_rule", UpsertAceMirrorRuleReducer),
  __reducerSchema("upsert_character", UpsertCharacterReducer),
  __reducerSchema("upsert_economy_limit", UpsertEconomyLimitReducer),
  __reducerSchema("upsert_menu_action", UpsertMenuActionReducer),
  __reducerSchema("upsert_menu_definition", UpsertMenuDefinitionReducer),
  __reducerSchema("upsert_menu_visibility_policy", UpsertMenuVisibilityPolicyReducer),
  __reducerSchema("upsert_plugin_capability", UpsertPluginCapabilityReducer),
  __reducerSchema("upsert_plugin_deployment", UpsertPluginDeploymentReducer),
  __reducerSchema("upsert_plugin_entity", UpsertPluginEntityReducer),
  __reducerSchema("upsert_plugin_runtime_instance", UpsertPluginRuntimeInstanceReducer),
  __reducerSchema("upsert_policy_constraint", UpsertPolicyConstraintReducer),
  __reducerSchema("upsert_principal", UpsertPrincipalReducer),
  __reducerSchema("upsert_runtime_command", UpsertRuntimeCommandReducer),
  __reducerSchema("upsert_runtime_panel", UpsertRuntimePanelReducer),
  __reducerSchema("void_transaction", VoidTransactionReducer),
  __reducerSchema("withdraw_cash", WithdrawCashReducer),
  __reducerSchema("write_audit_log", WriteAuditLogReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.2.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

