// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  issuerAccountId: __t.string().name("issuer_account_id"),
  payerAccountId: __t.string().name("payer_account_id"),
  amount: __t.i128(),
  currency: __t.string(),
  reason: __t.string(),
  status: __t.string(),
  issuedBy: __t.string().name("issued_by"),
  idempotencyKey: __t.string().name("idempotency_key"),
  issuedAt: __t.timestamp().name("issued_at"),
  dueAt: __t.option(__t.timestamp()).name("due_at"),
  paidAt: __t.option(__t.timestamp()).name("paid_at"),
});
