// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  issuerAccountId: __t.string(),
  payerAccountId: __t.string(),
  amount: __t.i128(),
  currency: __t.string(),
  reason: __t.string(),
  issuedBy: __t.string(),
  idempotencyKey: __t.string(),
  dueAt: __t.option(__t.timestamp()),
};
