// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  transactionId: __t.string().name("transaction_id"),
  accountId: __t.string().name("account_id"),
  direction: __t.string(),
  amount: __t.i128(),
  reason: __t.string(),
  metadataJson: __t.string().name("metadata_json"),
  createdAt: __t.timestamp().name("created_at"),
});
