// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  pluginId: __t.string().name("plugin_id"),
  label: __t.string(),
  parentId: __t.string().name("parent_id"),
  icon: __t.string(),
  order: __t.i32(),
  requiredPermission: __t.string().name("required_permission"),
  actionId: __t.string().name("action_id"),
  enabled: __t.bool(),
  visibilityPolicyId: __t.string().name("visibility_policy_id"),
});
