// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  pluginId: __t.string().name("plugin_id"),
  actionType: __t.string().name("action_type"),
  reducerName: __t.string().name("reducer_name"),
  payloadSchemaJson: __t.string().name("payload_schema_json"),
  confirmationRequired: __t.bool().name("confirmation_required"),
  auditLevel: __t.string().name("audit_level"),
  requiredPermission: __t.string().name("required_permission"),
  enabled: __t.bool(),
});
