// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  serverId: __t.string().name("server_id"),
  playerId: __t.string().name("player_id"),
  openedAt: __t.timestamp().name("opened_at"),
  closedAt: __t.option(__t.timestamp()).name("closed_at"),
  cacheVersion: __t.u64().name("cache_version"),
});
