// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  pluginId: __t.string().name("plugin_id"),
  serverId: __t.string().name("server_id"),
  status: __t.string(),
  loadedAt: __t.option(__t.timestamp()).name("loaded_at"),
  lastHeartbeat: __t.timestamp().name("last_heartbeat"),
  errorMessage: __t.string().name("error_message"),
});
