// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  pluginId: __t.string().name("plugin_id"),
  version: __t.string(),
  artifactUrl: __t.string().name("artifact_url"),
  bundleHash: __t.string().name("bundle_hash"),
  signature: __t.string(),
  signerId: __t.string().name("signer_id"),
  runtimeType: __t.string().name("runtime_type"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
