// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  pluginId: __t.string().name("plugin_id"),
  bundleId: __t.string().name("bundle_id"),
  capabilityKey: __t.string().name("capability_key"),
  constraintsJson: __t.string().name("constraints_json"),
  status: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
