// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  packageId: __t.string().primaryKey().name("package_id"),
  pluginId: __t.string().name("plugin_id"),
  version: __t.string(),
  source: __t.string(),
  publisher: __t.string(),
  trustLevel: __t.string().name("trust_level"),
  signerId: __t.string().name("signer_id"),
  signature: __t.string(),
  manifestHash: __t.string().name("manifest_hash"),
  installedAt: __t.timestamp().name("installed_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
