// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  pluginId: __t.string().primaryKey().name("plugin_id"),
  manifestJson: __t.string().name("manifest_json"),
  requiredPermissions: __t.string().name("required_permissions"),
  requiredTables: __t.string().name("required_tables"),
  requiredHooks: __t.string().name("required_hooks"),
  requiredConnectors: __t.string().name("required_connectors"),
  schemaVersion: __t.u64().name("schema_version"),
  updatedAt: __t.timestamp().name("updated_at"),
});
