// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  pluginId: __t.string().name("plugin_id"),
  schemaVersion: __t.u64().name("schema_version"),
  entityType: __t.string().name("entity_type"),
  schemaJson: __t.string().name("schema_json"),
  migrationPlanJson: __t.string().name("migration_plan_json"),
  status: __t.string(),
  registeredAt: __t.timestamp().name("registered_at"),
});
