// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  signerId: __t.string().primaryKey().name("signer_id"),
  actorId: __t.string().name("actor_id"),
  reason: __t.string(),
  affectedPluginIdsJson: __t.string().name("affected_plugin_ids_json"),
  revokedAt: __t.timestamp().name("revoked_at"),
});
