// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  pluginId: __t.string(),
  manifestJson: __t.string(),
  requiredPermissions: __t.string(),
  requiredTables: __t.string(),
  requiredHooks: __t.string(),
  requiredConnectors: __t.string(),
  schemaVersion: __t.u64(),
};
