// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  pluginId: __t.string(),
  version: __t.string(),
  artifactUrl: __t.string(),
  bundleHash: __t.string(),
  signature: __t.string(),
  signerId: __t.string(),
  runtimeType: __t.string(),
  status: __t.string(),
};
