// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  serverId: __t.string().name("server_id"),
  resourceVersion: __t.string().name("resource_version"),
  fxserverBuild: __t.string().name("fxserver_build"),
  gameBuild: __t.string().name("game_build"),
  status: __t.string(),
  startedAt: __t.timestamp().name("started_at"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
});
