// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  pluginId: __t.string().name("plugin_id"),
  name: __t.string(),
  aliasesJson: __t.string().name("aliases_json"),
  actionId: __t.string().name("action_id"),
  requiredPermission: __t.string().name("required_permission"),
  payloadSchemaJson: __t.string().name("payload_schema_json"),
  auditLevel: __t.string().name("audit_level"),
  enabled: __t.bool(),
});
