// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  id: __t.string(),
  ownerType: __t.string(),
  ownerId: __t.string(),
  currency: __t.string(),
  balance: __t.i128(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const AceMirrorRule = __t.object("AceMirrorRule", {
  id: __t.string(),
  permissionKey: __t.string(),
  aceObject: __t.string(),
  enabled: __t.bool(),
  mode: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AceMirrorRule = __Infer<typeof AceMirrorRule>;

export const AuditLog = __t.object("AuditLog", {
  id: __t.string(),
  serverId: __t.string(),
  actorId: __t.string(),
  pluginId: __t.string(),
  actionType: __t.string(),
  permissionKey: __t.string(),
  targetType: __t.string(),
  targetId: __t.string(),
  beforeJson: __t.string(),
  afterJson: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type AuditLog = __Infer<typeof AuditLog>;

export const Character = __t.object("Character", {
  id: __t.string(),
  playerPrincipalId: __t.string(),
  citizenId: __t.string(),
  cid: __t.u64(),
  slot: __t.u64(),
  license: __t.string(),
  name: __t.string(),
  charinfoJson: __t.string(),
  metadataJson: __t.string(),
  gangJson: __t.string(),
  positionJson: __t.string(),
  phoneNumber: __t.string(),
  accountNumber: __t.string(),
  selected: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type Character = __Infer<typeof Character>;

export const CharacterJob = __t.object("CharacterJob", {
  characterId: __t.string(),
  jobKey: __t.string(),
  grade: __t.string(),
  onDuty: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type CharacterJob = __Infer<typeof CharacterJob>;

export const EconomyLimit = __t.object("EconomyLimit", {
  id: __t.string(),
  permissionKey: __t.string(),
  actionType: __t.string(),
  limitJson: __t.string(),
  enabled: __t.bool(),
});
export type EconomyLimit = __Infer<typeof EconomyLimit>;

export const HeartbeatNonce = __t.object("HeartbeatNonce", {
  id: __t.string(),
  serverId: __t.string(),
  nonce: __t.string(),
  signature: __t.string(),
  seenAt: __t.timestamp(),
});
export type HeartbeatNonce = __Infer<typeof HeartbeatNonce>;

export const InventoryStack = __t.object("InventoryStack", {
  id: __t.string(),
  ownerId: __t.string(),
  itemKey: __t.string(),
  quantity: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type InventoryStack = __Infer<typeof InventoryStack>;

export const Invoice = __t.object("Invoice", {
  id: __t.string(),
  issuerAccountId: __t.string(),
  payerAccountId: __t.string(),
  amount: __t.i128(),
  currency: __t.string(),
  reason: __t.string(),
  status: __t.string(),
  issuedBy: __t.string(),
  idempotencyKey: __t.string(),
  issuedAt: __t.timestamp(),
  dueAt: __t.option(__t.timestamp()),
  paidAt: __t.option(__t.timestamp()),
});
export type Invoice = __Infer<typeof Invoice>;

export const Item = __t.object("Item", {
  key: __t.string(),
  pluginId: __t.string(),
  label: __t.string(),
  stackable: __t.bool(),
  maxStack: __t.u64(),
});
export type Item = __Infer<typeof Item>;

export const Job = __t.object("Job", {
  key: __t.string(),
  pluginId: __t.string(),
  label: __t.string(),
  gradesJson: __t.string(),
});
export type Job = __Infer<typeof Job>;

export const LedgerEntry = __t.object("LedgerEntry", {
  id: __t.string(),
  transactionId: __t.string(),
  accountId: __t.string(),
  direction: __t.string(),
  amount: __t.i128(),
  reason: __t.string(),
  metadataJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type LedgerEntry = __Infer<typeof LedgerEntry>;

export const Location = __t.object("Location", {
  key: __t.string(),
  pluginId: __t.string(),
  label: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
});
export type Location = __Infer<typeof Location>;

export const MenuAction = __t.object("MenuAction", {
  id: __t.string(),
  pluginId: __t.string(),
  actionType: __t.string(),
  reducerName: __t.string(),
  payloadSchemaJson: __t.string(),
  confirmationRequired: __t.bool(),
  auditLevel: __t.string(),
  requiredPermission: __t.string(),
  enabled: __t.bool(),
});
export type MenuAction = __Infer<typeof MenuAction>;

export const MenuDefinition = __t.object("MenuDefinition", {
  id: __t.string(),
  pluginId: __t.string(),
  label: __t.string(),
  parentId: __t.string(),
  icon: __t.string(),
  order: __t.i32(),
  requiredPermission: __t.string(),
  actionId: __t.string(),
  enabled: __t.bool(),
  visibilityPolicyId: __t.string(),
});
export type MenuDefinition = __Infer<typeof MenuDefinition>;

export const MenuSession = __t.object("MenuSession", {
  id: __t.string(),
  serverId: __t.string(),
  playerId: __t.string(),
  openedAt: __t.timestamp(),
  closedAt: __t.option(__t.timestamp()),
  cacheVersion: __t.u64(),
});
export type MenuSession = __Infer<typeof MenuSession>;

export const MenuVisibilityPolicy = __t.object("MenuVisibilityPolicy", {
  id: __t.string(),
  pluginId: __t.string(),
  policyJson: __t.string(),
  enabled: __t.bool(),
});
export type MenuVisibilityPolicy = __Infer<typeof MenuVisibilityPolicy>;

export const Permission = __t.object("Permission", {
  id: __t.string(),
  key: __t.string(),
  description: __t.string(),
  pluginId: __t.string(),
  createdAt: __t.timestamp(),
});
export type Permission = __Infer<typeof Permission>;

export const PermissionCacheVersion = __t.object("PermissionCacheVersion", {
  serverId: __t.string(),
  version: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type PermissionCacheVersion = __Infer<typeof PermissionCacheVersion>;

export const PermissionGrant = __t.object("PermissionGrant", {
  id: __t.string(),
  principalId: __t.string(),
  permissionKey: __t.string(),
  effect: __t.string(),
  source: __t.string(),
  expiresAt: __t.option(__t.timestamp()),
});
export type PermissionGrant = __Infer<typeof PermissionGrant>;

export const Plugin = __t.object("Plugin", {
  id: __t.string(),
  name: __t.string(),
  version: __t.string(),
  status: __t.string(),
  trustLevel: __t.string(),
  signature: __t.string(),
  bundleHash: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Plugin = __Infer<typeof Plugin>;

export const PluginBundle = __t.object("PluginBundle", {
  id: __t.string(),
  pluginId: __t.string(),
  version: __t.string(),
  artifactUrl: __t.string(),
  bundleHash: __t.string(),
  signature: __t.string(),
  signerId: __t.string(),
  runtimeType: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type PluginBundle = __Infer<typeof PluginBundle>;

export const PluginCapability = __t.object("PluginCapability", {
  id: __t.string(),
  pluginId: __t.string(),
  bundleId: __t.string(),
  capabilityKey: __t.string(),
  constraintsJson: __t.string(),
  status: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PluginCapability = __Infer<typeof PluginCapability>;

export const PluginConfigValue = __t.object("PluginConfigValue", {
  id: __t.string(),
  pluginId: __t.string(),
  serverId: __t.string(),
  key: __t.string(),
  valueJson: __t.string(),
  version: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type PluginConfigValue = __Infer<typeof PluginConfigValue>;

export const PluginDeployment = __t.object("PluginDeployment", {
  id: __t.string(),
  pluginId: __t.string(),
  bundleId: __t.string(),
  serverId: __t.string(),
  status: __t.string(),
  desiredVersion: __t.string(),
  activeVersion: __t.string(),
  deployedAt: __t.option(__t.timestamp()),
  errorMessage: __t.string(),
});
export type PluginDeployment = __Infer<typeof PluginDeployment>;

export const PluginEntity = __t.object("PluginEntity", {
  id: __t.string(),
  pluginId: __t.string(),
  entityType: __t.string(),
  ownerType: __t.string(),
  ownerId: __t.string(),
  dataJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PluginEntity = __Infer<typeof PluginEntity>;

export const PluginHook = __t.object("PluginHook", {
  id: __t.string(),
  pluginId: __t.string(),
  hookName: __t.string(),
  capability: __t.string(),
  handlerType: __t.string(),
  handlerRef: __t.string(),
  priority: __t.i32(),
  enabled: __t.bool(),
});
export type PluginHook = __Infer<typeof PluginHook>;

export const PluginManifest = __t.object("PluginManifest", {
  pluginId: __t.string(),
  manifestJson: __t.string(),
  requiredPermissions: __t.string(),
  requiredTables: __t.string(),
  requiredHooks: __t.string(),
  requiredConnectors: __t.string(),
  schemaVersion: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type PluginManifest = __Infer<typeof PluginManifest>;

export const PluginPackage = __t.object("PluginPackage", {
  packageId: __t.string(),
  pluginId: __t.string(),
  version: __t.string(),
  source: __t.string(),
  publisher: __t.string(),
  trustLevel: __t.string(),
  signerId: __t.string(),
  signature: __t.string(),
  manifestHash: __t.string(),
  installedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PluginPackage = __Infer<typeof PluginPackage>;

export const PluginPackageSignerRevocation = __t.object("PluginPackageSignerRevocation", {
  signerId: __t.string(),
  actorId: __t.string(),
  reason: __t.string(),
  affectedPluginIdsJson: __t.string(),
  revokedAt: __t.timestamp(),
});
export type PluginPackageSignerRevocation = __Infer<typeof PluginPackageSignerRevocation>;

export const PluginRuntimeInstance = __t.object("PluginRuntimeInstance", {
  id: __t.string(),
  pluginId: __t.string(),
  serverId: __t.string(),
  status: __t.string(),
  loadedAt: __t.option(__t.timestamp()),
  lastHeartbeat: __t.timestamp(),
  errorMessage: __t.string(),
});
export type PluginRuntimeInstance = __Infer<typeof PluginRuntimeInstance>;

export const PluginSandboxEvent = __t.object("PluginSandboxEvent", {
  id: __t.string(),
  pluginId: __t.string(),
  serverId: __t.string(),
  eventType: __t.string(),
  payloadHash: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type PluginSandboxEvent = __Infer<typeof PluginSandboxEvent>;

export const PluginSchema = __t.object("PluginSchema", {
  id: __t.string(),
  pluginId: __t.string(),
  schemaVersion: __t.u64(),
  entityType: __t.string(),
  schemaJson: __t.string(),
  migrationPlanJson: __t.string(),
  status: __t.string(),
  registeredAt: __t.timestamp(),
});
export type PluginSchema = __Infer<typeof PluginSchema>;

export const PolicyConstraint = __t.object("PolicyConstraint", {
  id: __t.string(),
  permissionKey: __t.string(),
  constraintType: __t.string(),
  constraintJson: __t.string(),
  priority: __t.i32(),
  enabled: __t.bool(),
});
export type PolicyConstraint = __Infer<typeof PolicyConstraint>;

export const Principal = __t.object("Principal", {
  id: __t.string(),
  principalType: __t.string(),
  externalId: __t.string(),
  name: __t.string(),
  createdAt: __t.timestamp(),
});
export type Principal = __Infer<typeof Principal>;

export const PrincipalEdge = __t.object("PrincipalEdge", {
  id: __t.string(),
  parentPrincipalId: __t.string(),
  childPrincipalId: __t.string(),
  source: __t.string(),
  expiresAt: __t.option(__t.timestamp()),
});
export type PrincipalEdge = __Infer<typeof PrincipalEdge>;

export const RuntimeAction = __t.object("RuntimeAction", {
  id: __t.string(),
  serverId: __t.string(),
  actorId: __t.string(),
  actionType: __t.string(),
  payloadHash: __t.string(),
  signature: __t.string(),
  nonce: __t.string(),
  idempotencyKey: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
});
export type RuntimeAction = __Infer<typeof RuntimeAction>;

export const RuntimeCommand = __t.object("RuntimeCommand", {
  id: __t.string(),
  pluginId: __t.string(),
  name: __t.string(),
  aliasesJson: __t.string(),
  actionId: __t.string(),
  requiredPermission: __t.string(),
  payloadSchemaJson: __t.string(),
  auditLevel: __t.string(),
  enabled: __t.bool(),
});
export type RuntimeCommand = __Infer<typeof RuntimeCommand>;

export const RuntimeConfig = __t.object("RuntimeConfig", {
  id: __t.string(),
  serverId: __t.string(),
  namespace: __t.string(),
  key: __t.string(),
  valueJson: __t.string(),
  version: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type RuntimeConfig = __Infer<typeof RuntimeConfig>;

export const RuntimeConfigAck = __t.object("RuntimeConfigAck", {
  id: __t.string(),
  serverId: __t.string(),
  namespace: __t.string(),
  key: __t.string(),
  version: __t.u64(),
  acknowledgedAt: __t.timestamp(),
});
export type RuntimeConfigAck = __Infer<typeof RuntimeConfigAck>;

export const RuntimeInstance = __t.object("RuntimeInstance", {
  id: __t.string(),
  serverId: __t.string(),
  resourceVersion: __t.string(),
  fxserverBuild: __t.string(),
  gameBuild: __t.string(),
  status: __t.string(),
  startedAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type RuntimeInstance = __Infer<typeof RuntimeInstance>;

export const RuntimePanel = __t.object("RuntimePanel", {
  id: __t.string(),
  pluginId: __t.string(),
  title: __t.string(),
  route: __t.string(),
  requiredPermission: __t.string(),
  icon: __t.string(),
  order: __t.i32(),
  enabled: __t.bool(),
});
export type RuntimePanel = __Infer<typeof RuntimePanel>;

export const Server = __t.object("Server", {
  id: __t.string(),
  name: __t.string(),
  environment: __t.string(),
  publicKey: __t.string(),
  status: __t.string(),
  lastHeartbeatAt: __t.timestamp(),
});
export type Server = __Infer<typeof Server>;

export const Transaction = __t.object("Transaction", {
  id: __t.string(),
  transactionType: __t.string(),
  actorId: __t.string(),
  status: __t.string(),
  idempotencyKey: __t.string(),
  metadataJson: __t.string(),
  createdAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
});
export type Transaction = __Infer<typeof Transaction>;

export const Vehicle = __t.object("Vehicle", {
  model: __t.string(),
  pluginId: __t.string(),
  label: __t.string(),
  category: __t.string(),
});
export type Vehicle = __Infer<typeof Vehicle>;

