// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  pluginId: __t.string(),
  name: __t.string(),
  aliasesJson: __t.string(),
  actionId: __t.string(),
  requiredPermission: __t.string(),
  payloadSchemaJson: __t.string(),
  auditLevel: __t.string(),
  enabled: __t.bool(),
};
