// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  playerPrincipalId: __t.string(),
  citizenId: __t.string(),
  cid: __t.u64(),
  slot: __t.u64(),
  license: __t.string(),
  name: __t.string(),
  charinfoJson: __t.string(),
  metadataJson: __t.string(),
  gangJson: __t.string(),
  positionJson: __t.string(),
  phoneNumber: __t.string(),
  accountNumber: __t.string(),
  selected: __t.bool(),
};
