// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  pluginId: __t.string(),
  label: __t.string(),
  parentId: __t.string(),
  icon: __t.string(),
  order: __t.i32(),
  requiredPermission: __t.string(),
  actionId: __t.string(),
  enabled: __t.bool(),
  visibilityPolicyId: __t.string(),
};
