// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  serverId: __t.string(),
  actorId: __t.string(),
  pluginId: __t.string(),
  actionType: __t.string(),
  permissionKey: __t.string(),
  targetType: __t.string(),
  targetId: __t.string(),
  beforeJson: __t.string(),
  afterJson: __t.string(),
  status: __t.string(),
};
